/* The following code was generated by JFlex 1.4.3 on 17/11/25, 18:57 */

package codigo;
import static codigo.Tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 17/11/25, 18:57 from the specification file
 * <tt>C:/Users/alanc/OneDrive/Documents/Tec/11vo Semestre/Lenguajes y Automatas 1/Unidad 4/Proyecto Compilador/quimcode-compilador/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\10\2\0\1\2\22\0\1\2\1\51\1\6\1\11"+
    "\1\0\1\26\1\54\1\0\1\56\1\57\1\46\1\45\1\64\1\5"+
    "\1\4\1\47\12\3\1\65\1\66\1\52\1\50\1\53\2\0\2\1"+
    "\1\20\1\1\1\1\5\1\1\20\1\20\1\20\2\1\1\23\12\1"+
    "\1\62\1\7\1\63\1\0\1\12\1\0\1\21\1\24\1\35\1\40"+
    "\1\33\1\32\1\16\1\34\1\30\1\44\1\17\1\15\1\13\1\31"+
    "\1\14\1\36\1\41\1\25\1\27\1\22\1\37\1\43\1\1\2\1"+
    "\1\42\1\60\1\55\1\61\103\0\1\67\7\0\1\67\3\0\1\67"+
    "\3\0\1\67\1\0\1\67\6\0\1\67\1\0\1\67\4\0\1\67"+
    "\7\0\1\67\3\0\1\67\3\0\1\67\1\0\1\67\6\0\1\67"+
    "\1\0\1\67\uff03\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\3\1\10\6\2\1\5\11\2\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\2\1\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\10\1\31"+
    "\1\10\1\32\3\10\1\32\1\31\1\33\1\34\1\7"+
    "\1\0\12\2\1\35\20\2\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\4\4\10\1\0\43\2\4\0\20\2"+
    "\1\44\17\2\1\45\3\2\4\0\1\46\5\2\1\47"+
    "\26\2\1\50\17\2\1\51\1\52\2\2\1\53\5\2"+
    "\1\54\3\2\1\55\13\2\1\56\3\2\1\57\1\60"+
    "\1\61\1\62\1\63\3\2\1\64\6\2\1\65\13\2"+
    "\1\66\2\2\1\67\1\2\1\70\1\71\1\72\3\2"+
    "\1\73\1\74\1\2\1\75\2\2\1\76\2\2\1\77"+
    "\1\100\1\101\11\2\1\102\1\103\2\2\1\104\7\2"+
    "\1\105\3\2\1\106\4\2\1\107\2\2\1\110\3\2"+
    "\1\111\1\2\1\112\1\113\10\2\1\114\1\115";

  private static int [] zzUnpackAction() {
    int [] result = new int[351];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\u0150\0\u0188"+
    "\0\u01c0\0\u01f8\0\u0230\0\u0268\0\u02a0\0\u02d8\0\u0310\0\u0348"+
    "\0\70\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498\0\u04d0"+
    "\0\u0508\0\u0540\0\u0150\0\u0150\0\u0150\0\u0578\0\u05b0\0\u05e8"+
    "\0\u0620\0\u0658\0\u0690\0\70\0\70\0\70\0\70\0\70"+
    "\0\70\0\70\0\70\0\70\0\u06c8\0\u0700\0\u0738\0\u06c8"+
    "\0\u0770\0\u07a8\0\u07e0\0\70\0\u0118\0\u0818\0\70\0\u0850"+
    "\0\u0888\0\u08c0\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u09d8\0\u0a10"+
    "\0\u0a48\0\u0a80\0\u0ab8\0\u0af0\0\u0b28\0\u0b60\0\u0b98\0\u0bd0"+
    "\0\u0c08\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8\0\u0d20\0\u0d58\0\u0d90"+
    "\0\u0dc8\0\u0e00\0\u0e38\0\u0e70\0\70\0\70\0\70\0\70"+
    "\0\70\0\70\0\u0ea8\0\u0ee0\0\u0f18\0\u0f50\0\u0f88\0\u0fc0"+
    "\0\u0ff8\0\u1030\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180"+
    "\0\u11b8\0\u11f0\0\u1228\0\u1260\0\u1298\0\u12d0\0\u1308\0\u1340"+
    "\0\u1378\0\u13b0\0\u13e8\0\u1420\0\u1458\0\u1490\0\u14c8\0\u1500"+
    "\0\u1538\0\u1570\0\u15a8\0\u15e0\0\u1618\0\u1650\0\u1688\0\u16c0"+
    "\0\u16f8\0\u1730\0\u1768\0\u17a0\0\u17d8\0\u1810\0\u1848\0\u1880"+
    "\0\u18b8\0\u18f0\0\u1928\0\u1960\0\u1998\0\u19d0\0\u1a08\0\u1a40"+
    "\0\u1a78\0\u1ab0\0\u1ae8\0\u1b20\0\u1b58\0\u1b90\0\u1bc8\0\u1c00"+
    "\0\u1c38\0\u1c70\0\u1ca8\0\u1ce0\0\u1d18\0\u1d50\0\u1d88\0\u1dc0"+
    "\0\u1df8\0\u1e30\0\u1e68\0\u1ea0\0\u1ed8\0\u1f10\0\u1f48\0\160"+
    "\0\u1f80\0\u1fb8\0\u1ff0\0\u2028\0\u2060\0\u2098\0\u20d0\0\160"+
    "\0\u2108\0\u2140\0\u2178\0\u21b0\0\u21e8\0\160\0\u2220\0\u2258"+
    "\0\u2290\0\u22c8\0\u2300\0\u2338\0\u2370\0\u23a8\0\u23e0\0\u2418"+
    "\0\u2450\0\u2488\0\u24c0\0\u24f8\0\u2530\0\u2568\0\u25a0\0\u25d8"+
    "\0\u2610\0\u2648\0\u2680\0\u26b8\0\160\0\u26f0\0\u2728\0\u2760"+
    "\0\u2798\0\u27d0\0\u2808\0\u2840\0\u2878\0\u28b0\0\u28e8\0\u2920"+
    "\0\u2958\0\u2990\0\u29c8\0\u2a00\0\160\0\160\0\u2a38\0\u2a70"+
    "\0\160\0\u2aa8\0\u2ae0\0\u2b18\0\u2b50\0\u2b88\0\160\0\u2bc0"+
    "\0\u2bf8\0\u2c30\0\160\0\u2c68\0\u2ca0\0\u2cd8\0\u2d10\0\u2d48"+
    "\0\u2d80\0\u2db8\0\u2df0\0\u2e28\0\u2e60\0\u2e98\0\u2ed0\0\u2f08"+
    "\0\u2f40\0\u2f78\0\160\0\160\0\160\0\160\0\160\0\u2fb0"+
    "\0\u2fe8\0\u3020\0\160\0\u3058\0\u3090\0\u30c8\0\u3100\0\u3138"+
    "\0\u3170\0\160\0\u31a8\0\u31e0\0\u3218\0\u3250\0\u3288\0\u32c0"+
    "\0\u32f8\0\u3330\0\u3368\0\u33a0\0\u33d8\0\160\0\u3410\0\u3448"+
    "\0\160\0\u3480\0\160\0\160\0\160\0\u34b8\0\u34f0\0\u3528"+
    "\0\160\0\160\0\u3560\0\160\0\u3598\0\u35d0\0\160\0\u3608"+
    "\0\u3640\0\160\0\160\0\160\0\u3678\0\u36b0\0\u36e8\0\u3720"+
    "\0\u3758\0\u3790\0\u37c8\0\u3800\0\u3838\0\160\0\160\0\u3870"+
    "\0\u38a8\0\160\0\u38e0\0\u3918\0\u3950\0\u3988\0\u39c0\0\u39f8"+
    "\0\u3a30\0\160\0\u3a68\0\u3aa0\0\u3ad8\0\160\0\u3b10\0\u3b48"+
    "\0\u3b80\0\u3bb8\0\160\0\u3bf0\0\u3c28\0\160\0\u3c60\0\u3c98"+
    "\0\u3cd0\0\160\0\u3d08\0\160\0\160\0\u3d40\0\u3d78\0\u3db0"+
    "\0\u3de8\0\u3e20\0\u3e58\0\u3e90\0\u3ec8\0\160\0\160";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[351];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\4\1\11\1\12\1\13\1\3\1\14\1\15\2\3"+
    "\1\16\2\3\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\3\1\32\4\3"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\21\71\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\16\3\25\0\1\4\5\0\1\4\60\0"+
    "\1\55\1\0\1\5\1\56\5\0\1\55\1\57\2\55"+
    "\1\60\1\61\1\60\1\62\2\55\1\63\1\55\1\64"+
    "\16\55\26\0\1\65\65\0\1\66\10\0\14\66\1\0"+
    "\16\66\23\0\6\10\1\67\1\70\1\71\57\10\10\11"+
    "\1\0\57\11\1\0\1\3\1\0\1\55\6\0\1\55"+
    "\13\3\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\2\3\1\72\11\3\1\0\1\3\1\73\2\3\1\74"+
    "\11\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\1\3\1\75\14\3\24\0\1\3\1\0\1\3\6\0"+
    "\7\3\1\76\4\3\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\4\3\1\77\7\3\1\0\6\3\1\100"+
    "\7\3\24\0\1\3\1\0\1\3\6\0\7\3\1\101"+
    "\4\3\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\4\3\1\102\11\3\24\0\1\3\1\0"+
    "\1\3\6\0\2\3\1\103\11\3\1\0\1\3\1\104"+
    "\14\3\24\0\1\3\1\0\1\3\6\0\1\3\1\105"+
    "\12\3\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\4\3\1\106\11\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\1\3\1\107\14\3\24\0"+
    "\1\3\1\0\1\3\6\0\3\3\1\110\10\3\1\0"+
    "\1\111\1\3\1\112\11\3\1\113\1\114\24\0\1\3"+
    "\1\0\1\3\6\0\7\3\1\115\4\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\2\3\1\116\4\3"+
    "\1\117\4\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\13\3\1\120\1\0\4\3\1\121\11\3\24\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\1\3\1\122"+
    "\2\3\1\123\3\3\1\124\5\3\24\0\1\66\10\0"+
    "\14\66\1\0\16\66\3\0\1\125\20\0\1\66\10\0"+
    "\14\66\1\0\16\66\3\0\1\126\20\0\1\66\10\0"+
    "\14\66\1\0\16\66\3\0\1\127\20\0\1\66\10\0"+
    "\14\66\1\0\16\66\3\0\1\130\20\0\1\66\10\0"+
    "\14\66\1\0\16\66\7\0\1\131\70\0\1\132\13\0"+
    "\1\55\1\0\1\55\6\0\14\55\1\0\16\55\26\0"+
    "\1\133\65\0\1\55\1\0\1\55\6\0\2\55\1\134"+
    "\1\60\10\55\1\0\16\55\24\0\1\55\1\0\1\55"+
    "\6\0\4\55\1\60\4\55\1\135\2\55\1\0\16\55"+
    "\24\0\1\55\1\0\1\55\6\0\10\55\1\136\3\55"+
    "\1\0\16\55\24\0\1\55\1\0\1\55\6\0\7\55"+
    "\1\137\4\55\1\0\16\55\24\0\1\66\1\0\1\66"+
    "\6\0\14\66\1\0\16\66\23\0\6\10\1\71\1\10"+
    "\1\0\57\10\6\71\1\67\1\140\60\71\1\0\1\3"+
    "\1\0\1\3\6\0\3\3\1\141\10\3\1\0\1\142"+
    "\15\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\4\3\1\143\11\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\11\3\1\144\1\3\1\145\2\3\24\0"+
    "\1\3\1\0\1\3\6\0\1\3\1\146\6\3\1\147"+
    "\3\3\1\0\12\3\1\150\3\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\1\151\15\3\24\0\1\3"+
    "\1\0\1\3\6\0\13\3\1\152\1\0\1\3\1\153"+
    "\14\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\10\3\1\154\5\3\24\0\1\3\1\0\1\3\6\0"+
    "\3\3\1\155\10\3\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\7\3\1\156\4\3\1\0\16\3\24\0"+
    "\1\3\1\0\1\3\6\0\3\3\1\157\10\3\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\2\3\1\160\13\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\7\3\1\161\6\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\10\3\1\162\5\3\24\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\2\3\1\163"+
    "\13\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\1\3\1\164\2\3\1\165\11\3\24\0\1\3\1\0"+
    "\1\3\6\0\10\3\1\166\3\3\1\0\16\3\24\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\3\3\1\167"+
    "\10\3\1\170\1\3\24\0\1\3\1\0\1\3\6\0"+
    "\7\3\1\171\4\3\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\4\3\1\172\11\3\24\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\6\3\1\173"+
    "\7\3\24\0\1\3\1\0\1\3\6\0\1\3\1\174"+
    "\12\3\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\3\3\1\175\10\3\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\1\3\1\176\2\3\1\177"+
    "\11\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\1\200\15\3\24\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\1\201\15\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\1\202\15\3\24\0\1\3\1\0\1\3"+
    "\6\0\13\3\1\203\1\0\16\3\26\0\1\133\7\0"+
    "\1\204\2\0\1\64\1\205\1\64\1\206\2\0\1\207"+
    "\1\0\1\64\42\0\1\55\1\0\1\55\6\0\3\55"+
    "\1\60\10\55\1\0\16\55\24\0\1\55\1\0\1\55"+
    "\6\0\7\55\1\60\4\55\1\0\16\55\24\0\1\55"+
    "\1\0\1\55\6\0\1\55\1\60\12\55\1\0\16\55"+
    "\24\0\1\55\1\0\1\55\6\0\13\55\1\60\1\0"+
    "\16\55\23\0\10\71\1\0\57\71\1\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\4\3\1\210\11\3\24\0"+
    "\1\3\1\0\1\3\6\0\10\3\1\211\3\3\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\2\3\1\212\13\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\1\3\1\213\14\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\6\3\1\214\7\3\24\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\7\3\1\215"+
    "\6\3\24\0\1\3\1\0\1\3\6\0\13\3\1\216"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\10\3\1\217\5\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\4\3\1\220\11\3\24\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\4\3\1\221\11\3"+
    "\24\0\1\3\1\0\1\3\6\0\10\3\1\222\3\3"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\2\3"+
    "\1\223\11\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\7\3\1\224\4\3\1\0\16\3\24\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\6\3\1\225\7\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\1\3"+
    "\1\226\6\3\1\227\5\3\24\0\1\3\1\0\1\3"+
    "\6\0\2\3\1\230\11\3\1\0\16\3\24\0\1\3"+
    "\1\0\1\3\6\0\13\3\1\231\1\0\16\3\24\0"+
    "\1\3\1\0\1\3\6\0\10\3\1\232\3\3\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\1\233\13\3"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\1\3"+
    "\1\234\12\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\1\3\1\235\12\3\1\0\16\3\24\0\1\3"+
    "\1\0\1\3\6\0\7\3\1\236\4\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\13\3\1\237\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\1\3\1\240\14\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\7\3\1\241\6\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\6\3\1\242\7\3\24\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\4\3\1\243"+
    "\11\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\7\3\1\244\6\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\4\3\1\245\11\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\2\3\1\246\13\3\24\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\6\3\1\247"+
    "\7\3\24\0\1\3\1\0\1\3\6\0\2\3\1\250"+
    "\11\3\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\2\3\1\251\11\3\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\10\3\1\252\3\3\1\0\16\3\24\0"+
    "\1\3\1\0\1\3\6\0\7\3\1\253\4\3\1\0"+
    "\16\3\37\0\1\254\1\64\70\0\1\64\4\0\1\255"+
    "\66\0\1\256\66\0\1\257\47\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\1\260\15\3\24\0\1\3\1\0"+
    "\1\3\6\0\13\3\1\261\1\0\16\3\24\0\1\3"+
    "\1\0\1\3\6\0\10\3\1\262\3\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\13\3\1\263\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\3\3\1\264"+
    "\10\3\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\1\3\1\265\14\3\24\0\1\3\1\0"+
    "\1\3\6\0\2\3\1\266\11\3\1\0\16\3\24\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\1\3\1\267"+
    "\14\3\24\0\1\3\1\0\1\3\6\0\2\3\1\270"+
    "\11\3\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\4\3\1\271\7\3\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\7\3\1\272\4\3\1\0\16\3\24\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\1\273\15\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\2\3"+
    "\1\274\13\3\24\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\6\3\1\275\7\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\11\3\1\276\4\3\24\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\6\3\1\277\7\3"+
    "\24\0\1\3\1\0\1\3\6\0\1\300\13\3\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\1\3\1\301\14\3\24\0\1\3\1\0\1\3\6\0"+
    "\13\3\1\302\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\1\3\1\303\12\3\1\0\1\304\6\3\1\305"+
    "\6\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\1\3\1\306\14\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\4\3\1\307\11\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\11\3\1\310\4\3\24\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\1\3\1\311"+
    "\14\3\24\0\1\3\1\0\1\3\6\0\7\3\1\312"+
    "\4\3\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\2\3\1\313\11\3\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\10\3\1\314\5\3\24\0"+
    "\1\3\1\0\1\3\6\0\13\3\1\315\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\10\3"+
    "\1\316\5\3\24\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\2\3\1\317\13\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\6\3\1\320\7\3\24\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\1\3\1\321\14\3"+
    "\24\0\1\3\1\0\1\3\6\0\3\3\1\322\10\3"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\1\3\1\323\14\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\6\3\1\324\7\3\40\0\1\64"+
    "\73\0\1\64\61\0\1\64\101\0\1\64\43\0\1\3"+
    "\1\0\1\3\6\0\7\3\1\325\4\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\13\3\1\326\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\1\327\13\3"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\7\3"+
    "\1\330\4\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\7\3\1\331\4\3\1\0\16\3\24\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\11\3\1\332\4\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\1\333"+
    "\15\3\24\0\1\3\1\0\1\3\6\0\7\3\1\334"+
    "\4\3\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\13\3\1\335\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\2\3\1\336\11\3\1\0\16\3\24\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\6\3\1\337\7\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\1\3"+
    "\1\340\14\3\24\0\1\3\1\0\1\3\6\0\2\3"+
    "\1\341\11\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\1\3\1\342\14\3\24\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\1\343\15\3\24\0"+
    "\1\3\1\0\1\3\6\0\1\3\1\344\12\3\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\7\3\1\345"+
    "\4\3\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\1\3\1\346\14\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\1\3\1\347\14\3\24\0"+
    "\1\3\1\0\1\3\6\0\13\3\1\350\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\2\3"+
    "\1\351\13\3\24\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\2\3\1\352\13\3\24\0\1\3\1\0\1\3"+
    "\6\0\2\3\1\353\11\3\1\0\16\3\24\0\1\3"+
    "\1\0\1\3\6\0\7\3\1\354\4\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\13\3\1\355\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\13\3\1\356"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\10\3"+
    "\1\357\3\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\4\3\1\360\11\3\24\0\1\3"+
    "\1\0\1\3\6\0\10\3\1\361\3\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\1\3"+
    "\1\362\14\3\24\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\7\3\1\363\6\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\14\3\1\364\1\3\24\0\1\3"+
    "\1\0\1\3\6\0\3\3\1\365\10\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\1\3"+
    "\1\366\14\3\24\0\1\3\1\0\1\3\6\0\13\3"+
    "\1\367\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\7\3\1\370\4\3\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\10\3\1\371\3\3\1\0\7\3\1\372"+
    "\6\3\24\0\1\3\1\0\1\3\6\0\13\3\1\373"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\13\3"+
    "\1\374\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\2\3\1\375\11\3\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\2\3\1\376\11\3\1\0\16\3\24\0"+
    "\1\3\1\0\1\3\6\0\13\3\1\377\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\4\3"+
    "\1\u0100\11\3\24\0\1\3\1\0\1\3\6\0\2\3"+
    "\1\u0101\11\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\2\3\1\u0102\11\3\1\0\16\3\24\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\1\3\1\u0103\14\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\1\3"+
    "\1\u0104\14\3\24\0\1\3\1\0\1\3\6\0\3\3"+
    "\1\u0105\10\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\4\3\1\u0106\11\3\24\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\1\3\1\u0107\14\3"+
    "\24\0\1\3\1\0\1\3\6\0\7\3\1\u0108\4\3"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\10\3"+
    "\1\u0109\3\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\13\3\1\u010a\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\1\u010b\13\3\1\0\16\3\24\0\1\3"+
    "\1\0\1\3\6\0\7\3\1\u010c\4\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\7\3\1\u010d\4\3"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\1\u010e\15\3\24\0\1\3\1\0\1\3\6\0"+
    "\7\3\1\u010f\4\3\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\7\3\1\u0110\6\3\24\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\1\3\1\u0111"+
    "\14\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\4\3\1\u0112\11\3\24\0\1\3\1\0\1\3\6\0"+
    "\7\3\1\u0113\4\3\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\2\3\1\u0114\11\3\1\0\16\3\24\0"+
    "\1\3\1\0\1\3\6\0\1\u0115\13\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\1\u0116"+
    "\15\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\4\3\1\u0117\11\3\24\0\1\3\1\0\1\3\6\0"+
    "\13\3\1\u0118\1\0\5\3\1\u0119\10\3\24\0\1\3"+
    "\1\0\1\3\6\0\7\3\1\u011a\4\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\2\3"+
    "\1\u011b\13\3\24\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\2\3\1\u011c\13\3\24\0\1\3\1\0\1\3"+
    "\6\0\13\3\1\u011d\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\1\3\1\u011e\14\3\24\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\2\3\1\u011f"+
    "\13\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\2\3\1\u0120\13\3\24\0\1\3\1\0\1\3\6\0"+
    "\13\3\1\u0121\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\2\3\1\u0122\11\3\1\0\16\3\24\0\1\3"+
    "\1\0\1\3\6\0\7\3\1\u0123\4\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\13\3\1\u0124\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\13\3\1\u0125"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\10\3"+
    "\1\u0126\3\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\13\3\1\u0127\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\7\3\1\u0128\4\3\1\0\16\3\24\0"+
    "\1\3\1\0\1\3\6\0\10\3\1\u0129\3\3\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\13\3\1\u012a"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\13\3"+
    "\1\u012b\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\2\3\1\u012c\13\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\1\3\1\u012d\14\3\24\0"+
    "\1\3\1\0\1\3\6\0\1\3\1\u012e\12\3\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\14\3\1\0"+
    "\4\3\1\u012f\11\3\24\0\1\3\1\0\1\3\6\0"+
    "\13\3\1\u0130\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\13\3\1\u0131\2\3\24\0\1\3"+
    "\1\0\1\3\6\0\10\3\1\u0132\3\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\6\3"+
    "\1\u0133\7\3\24\0\1\3\1\0\1\3\6\0\3\3"+
    "\1\u0134\10\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\1\u0135\13\3\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\2\3\1\u0136\11\3\1\0\16\3\24\0"+
    "\1\3\1\0\1\3\6\0\3\3\1\u0137\10\3\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\7\3\1\u0138"+
    "\4\3\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\2\3\1\u0139\13\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\7\3\1\u013a\6\3\24\0"+
    "\1\3\1\0\1\3\6\0\14\3\1\0\1\u013b\15\3"+
    "\24\0\1\3\1\0\1\3\6\0\1\u013c\13\3\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\7\3\1\u013d"+
    "\4\3\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\13\3\1\u013e\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\1\3\1\u013f\14\3\24\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\4\3\1\u0140\11\3"+
    "\24\0\1\3\1\0\1\3\6\0\13\3\1\u0141\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\13\3\1\u0142"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\3\3\1\u0143\12\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\1\3\1\u0144\14\3\24\0\1\3"+
    "\1\0\1\3\6\0\13\3\1\u0145\1\0\16\3\24\0"+
    "\1\3\1\0\1\3\6\0\13\3\1\u0146\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\7\3\1\u0147\4\3"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\7\3\1\u0148\6\3\24\0\1\3\1\0\1\3"+
    "\6\0\13\3\1\u0149\1\0\16\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\4\3\1\u014a\11\3\24\0"+
    "\1\3\1\0\1\3\6\0\2\3\1\u014b\11\3\1\0"+
    "\16\3\24\0\1\3\1\0\1\3\6\0\2\3\1\u014c"+
    "\11\3\1\0\16\3\24\0\1\3\1\0\1\3\6\0"+
    "\14\3\1\0\4\3\1\u014d\11\3\24\0\1\3\1\0"+
    "\1\3\6\0\14\3\1\0\1\u014e\15\3\24\0\1\3"+
    "\1\0\1\3\6\0\7\3\1\u014f\4\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\10\3\1\u0150\3\3"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\7\3"+
    "\1\u0151\4\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\2\3\1\u0152\13\3\24\0\1\3"+
    "\1\0\1\3\6\0\7\3\1\u0153\4\3\1\0\16\3"+
    "\24\0\1\3\1\0\1\3\6\0\3\3\1\u0154\10\3"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\7\3"+
    "\1\u0155\4\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\6\3\1\u0156\7\3\24\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\6\3\1\u0157\7\3"+
    "\24\0\1\3\1\0\1\3\6\0\14\3\1\0\6\3"+
    "\1\u0158\7\3\24\0\1\3\1\0\1\3\6\0\14\3"+
    "\1\0\6\3\1\u0159\7\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\1\3\1\u015a\14\3\24\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\1\3\1\u015b\14\3"+
    "\24\0\1\3\1\0\1\3\6\0\2\3\1\u015c\11\3"+
    "\1\0\16\3\24\0\1\3\1\0\1\3\6\0\2\3"+
    "\1\u015d\11\3\1\0\16\3\24\0\1\3\1\0\1\3"+
    "\6\0\14\3\1\0\2\3\1\u015e\13\3\24\0\1\3"+
    "\1\0\1\3\6\0\14\3\1\0\2\3\1\u015f\13\3"+
    "\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[16128];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\16\1\1\11\22\1\11\11\7\1\1\11"+
    "\2\1\1\11\1\1\1\0\33\1\6\11\5\1\1\0"+
    "\43\1\4\0\44\1\4\0\260\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[351];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private final TablaSimbolos tablaSimbolos = new TablaSimbolos();
    private final TablaFunciones tablaFunciones = new TablaFunciones();

    public TablaSimbolos getTablaSimbolos() {
        return this.tablaSimbolos;
    }

    public TablaFunciones getTablaFunciones() { 
        return this.tablaFunciones;
    }

    private Tokens token(String lex, String comp, int li, int c){
        return new Tokens(lex, comp, li+1, c+1); 
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 206) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 61: 
          { return token(yytext(),"TKN_EVAPORAR",yyline,yycolumn);
          }
        case 78: break;
        case 66: 
          { return token(yytext(),"TKN_COMPUESTO",yyline,yycolumn);
          }
        case 79: break;
        case 25: 
          { return token(yytext(),"ERROR_NUMERO_MALFORMADO",yyline,yycolumn);
          }
        case 80: break;
        case 57: 
          { return token(yytext(),"TKN_SOLUCION",yyline,yycolumn);
          }
        case 81: break;
        case 22: 
          { return token(yytext(),"COMA",yyline,yycolumn);
          }
        case 82: break;
        case 15: 
          { return token(yytext(),"OP_MAYOR",yyline,yycolumn);
          }
        case 83: break;
        case 16: 
          { return token(yytext(),"PAREN_ABRE",yyline,yycolumn);
          }
        case 84: break;
        case 39: 
          { return token(yytext(),"TKN_LITRO",yyline,yycolumn);
          }
        case 85: break;
        case 70: 
          { return token(yytext(),"TKN_NEUTRALIZAR",yyline,yycolumn);
          }
        case 86: break;
        case 59: 
          { return token(yytext(),"TKN_ELIMINAR",yyline,yycolumn);
          }
        case 87: break;
        case 36: 
          { return token(yytext(),"TKN_SINO",yyline,yycolumn);
          }
        case 88: break;
        case 23: 
          { return token(yytext(),"DOS_PUNTOS",yyline,yycolumn);
          }
        case 89: break;
        case 21: 
          { return token(yytext(),"CORCHETE_CIERRA",yyline,yycolumn);
          }
        case 90: break;
        case 20: 
          { return token(yytext(),"CORCHETE_ABRE",yyline,yycolumn);
          }
        case 91: break;
        case 32: 
          { return token(yytext(),"OP_MENOR_IGUAL",yyline,yycolumn);
          }
        case 92: break;
        case 63: 
          { return token(yytext(),"TKN_DISOLVER",yyline,yycolumn);
          }
        case 93: break;
        case 28: 
          { return token(yytext(),"CADENA",yyline,yycolumn);
          }
        case 94: break;
        case 75: 
          { return token(yytext(),"TKN_ENVIAR_ALERTA",yyline,yycolumn);
          }
        case 95: break;
        case 69: 
          { return token(yytext(),"TKN_PRECIPITAR",yyline,yycolumn);
          }
        case 96: break;
        case 73: 
          { return token(yytext(),"TKN_MEDIR_PRESION",yyline,yycolumn);
          }
        case 97: break;
        case 65: 
          { return token(yytext(),"TKN_DURACION",yyline,yycolumn);
          }
        case 98: break;
        case 46: 
          { return token(yytext(),"TKN_MOSTRAR",yyline,yycolumn);
          }
        case 99: break;
        case 60: 
          { return token(yytext(),"TKN_ELEMENTO",yyline,yycolumn);
          }
        case 100: break;
        case 1: 
          { return token(yytext(),"ERROR_CARACTER_INVALIDO",yyline,yycolumn);
          }
        case 101: break;
        case 33: 
          { return token(yytext(),"OP_MAYOR_IGUAL",yyline,yycolumn);
          }
        case 102: break;
        case 76: 
          { return token(yytext(),"TKN_EJECUTAR_REACCION",yyline,yycolumn);
          }
        case 103: break;
        case 12: 
          { return token(yytext(),"OP_ASIGN",yyline,yycolumn);
          }
        case 104: break;
        case 64: 
          { return token(yytext(),"TKN_DESTILAR",yyline,yycolumn);
          }
        case 105: break;
        case 7: 
          { return token(yytext(),"ERROR_CADENA_NO_CERRADA",yyline,yycolumn);
          }
        case 106: break;
        case 4: 
          { return token(yytext(),"NUMERO",yyline,yycolumn);
          }
        case 107: break;
        case 58: 
          { return token(yytext(),"TKN_IMPRIMIR",yyline,yycolumn);
          }
        case 108: break;
        case 43: 
          { return token(yytext(),"TKN_SOLIDO",yyline,yycolumn);
          }
        case 109: break;
        case 30: 
          { return token(yytext(),"OP_IGUAL",yyline,yycolumn);
          }
        case 110: break;
        case 17: 
          { return token(yytext(),"PAREN_CIERRA",yyline,yycolumn);
          }
        case 111: break;
        case 10: 
          { return token(yytext(),"OP_POR",yyline,yycolumn);
          }
        case 112: break;
        case 71: 
          { return token(yytext(),"TKN_MOSTRAR_INFO",yyline,yycolumn);
          }
        case 113: break;
        case 19: 
          { return token(yytext(),"LLAVE_CIERRA",yyline,yycolumn);
          }
        case 114: break;
        case 26: 
          { return token(yytext(),"LIT_NUMERICA",yyline,yycolumn);
          }
        case 115: break;
        case 41: 
          { return token(yytext(),"TKN_AGITAR",yyline,yycolumn);
          }
        case 116: break;
        case 11: 
          { return token(yytext(),"OP_DIV",yyline,yycolumn);
          }
        case 117: break;
        case 67: 
          { return token(yytext(),"TKN_PRINCIPAL",yyline,yycolumn);
          }
        case 118: break;
        case 34: 
          { return token(yytext(),"OP_AND",yyline,yycolumn);
          }
        case 119: break;
        case 35: 
          { return token(yytext(),"OP_OR",yyline,yycolumn);
          }
        case 120: break;
        case 51: 
          { return token(yytext(),"TKN_AGREGAR",yyline,yycolumn);
          }
        case 121: break;
        case 45: 
          { return token(yytext(),"TKN_ESTADO",yyline,yycolumn);
          }
        case 122: break;
        case 53: 
          { return token(yytext(),"TKN_ENFRIAR",yyline,yycolumn);
          }
        case 123: break;
        case 49: 
          { return token(yytext(),"TKN_LIQUIDO",yyline,yycolumn);
          }
        case 124: break;
        case 50: 
          { return token(yytext(),"TKN_GASEOSO",yyline,yycolumn);
          }
        case 125: break;
        case 55: 
          { return token(yytext(),"TKN_MEDIR_PH",yyline,yycolumn);
          }
        case 126: break;
        case 52: 
          { return token(yytext(),"TKN_SINO_SI",yyline,yycolumn);
          }
        case 127: break;
        case 29: 
          { return token(yytext(),"TKN_SI",yyline,yycolumn);
          }
        case 128: break;
        case 48: 
          { return token(yytext(),"TKN_LIMPIAR",yyline,yycolumn);
          }
        case 129: break;
        case 13: 
          { return token(yytext(),"OP_NOT",yyline,yycolumn);
          }
        case 130: break;
        case 31: 
          { return token(yytext(),"OP_DIF",yyline,yycolumn);
          }
        case 131: break;
        case 72: 
          { return token(yytext(),"TKN_FIN_MIENTRAS",yyline,yycolumn);
          }
        case 132: break;
        case 77: 
          { return token(yytext(),"TKN_BALANCEAR_REACCION",yyline,yycolumn);
          }
        case 133: break;
        case 8: 
          { return token(yytext(), "ERROR_IDENTIFICADOR_INVALIDO", yyline, yycolumn);
          }
        case 134: break;
        case 74: 
          { return token(yytext(),"TKN_FIN_PRINCIPAL",yyline,yycolumn);
          }
        case 135: break;
        case 5: 
          { return token(yytext(), "ERROR", yyline, yycolumn);
          }
        case 136: break;
        case 27: 
          { return token(yytext(), "ERROR_LEXICO", yyline, yycolumn);
          }
        case 137: break;
        case 24: 
          { return token(yytext(),"PUNTO_COMA",yyline,yycolumn);
          }
        case 138: break;
        case 56: 
          { return token(yytext(),"TKN_REACCION",yyline,yycolumn);
          }
        case 139: break;
        case 18: 
          { return token(yytext(),"LLAVE_ABRE",yyline,yycolumn);
          }
        case 140: break;
        case 37: 
          { return token(yytext(),"TKN_PESO",yyline,yycolumn);
          }
        case 141: break;
        case 2: 
          { // Revisa la "Tabla Fija"
        if (TablaPalabrasReservadas.esReservada(yytext())){
            return token(yytext(),"Error identificador es palabra reservada",yyline,yycolumn);
        } else {
            // Si no es reservada, la registra en la "Tabla de identificadores"
            tablaSimbolos.registrarIdentificador(yytext(), yyline+1, yycolumn+1);
            return token(yytext(),"IDENTIFICADOR",yyline,yycolumn);
        }
          }
        case 142: break;
        case 40: 
          { return token(yytext(),"TKN_HACER",yyline,yycolumn);
          }
        case 143: break;
        case 9: 
          { return token(yytext(),"OP_MAS",yyline,yycolumn);
          }
        case 144: break;
        case 3: 
          { /* ignorar */
          }
        case 145: break;
        case 62: 
          { return token(yytext(),"TKN_CALENTAR",yyline,yycolumn);
          }
        case 146: break;
        case 6: 
          { return token(yytext(),"OP_MENOS",yyline,yycolumn);
          }
        case 147: break;
        case 47: 
          { return token(yytext(),"TKN_MEZCLAR",yyline,yycolumn);
          }
        case 148: break;
        case 68: 
          { return token(yytext(),"TKN_MEDIR_TEMPERATURA",yyline,yycolumn);
          }
        case 149: break;
        case 14: 
          { return token(yytext(),"OP_MENOR",yyline,yycolumn);
          }
        case 150: break;
        case 54: 
          { return token(yytext(),"TKN_MIENTRAS",yyline,yycolumn);
          }
        case 151: break;
        case 42: 
          { return token(yytext(),"TKN_ACUOSO",yyline,yycolumn);
          }
        case 152: break;
        case 38: 
          { return token(yytext(),"TKN_MOLES",yyline,yycolumn);
          }
        case 153: break;
        case 44: 
          { return token(yytext(),"TKN_FIN_SI",yyline,yycolumn);
          }
        case 154: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
